#!/bin/bash

file=~/.bash_profile
cwd=$(pwd)

if ! [ -f "$file" ]; then
echo "$file created"
touch ~/.bash_profile
fi

if ! grep -i "$cwd/script" $file &>/dev/null; then
echo 'export PATH=$PATH"'":$(pwd)/script"'"' >> $file
fi

if ! grep -i 'export GITHUB_API_TOKEN=' $file &>/dev/null; then
echo "export GITHUB_API_TOKEN=$1" >> $file
fi

. ~/.bash_profile
