#!/usr/bin/env python

import argparse
import os
import http.client
import json

URL = "https://api.github.com/user/repos"
# Set your GitHub API Token as an environment variable to run this script
API_KEY = os.getenv('GITHUB_API_TOKEN')

if API_KEY is None:
  print("Please set environment variable 'GITHUB_API_TOKEN'")
  exit()

parser = argparse.ArgumentParser(description='creates a local repository linked with a remote repository')

parser.add_argument('path', metavar='PATH', type=str, help='Enter the path for the new repository')
parser.add_argument('name', metavar='NAME', type=str, help='Enter a name for the new repository')
args = parser.parse_args()

name = args.name
path = args.path

os.chdir(path)
os.mkdir(name)
os.chdir(name)
os.system('git init -b main')
os.system('touch README.md')
os.system('git add . && git commit -m "initial commit"')
# os.system('git status')

conn = http.client.HTTPSConnection("api.github.com")
payload = json.dumps({
  "name": name,
  "description": "made with the GitHub API"
})
headers = {
  'Authorization': f'Bearer {API_KEY}',
  'Content-Type': 'application/json',
  'User-Agent': 'sahil-sagwekar2652'
}

conn.request("POST", "/user/repos", payload, headers)
res = conn.getresponse()
data = res.read().decode("utf-8")
response = json.loads(data)

print(response)
remote_url = response['svn_url']

os.system(f'git remote add origin {remote_url}')
os.system('git push origin main')
print(f"\nREMOTE URL FOR \"{name}\" is: {remote_url}")

