#!/bin/bash

TOKEN=$(gum input --placeholder  "Git Token" --password)
NAME=$(gum input --placeholder "Username")


# echo -e "Well that's something,""$TOKEN"

if [ ! -f 'github_secrets.py' ]
then
    gum spin --spinner dot --title "Creating github_secrets.py" -- sleep 2 && echo "GITHUB_API_TOKEN = ""\"$TOKEN"\" >> github_secrets.py && echo "USERNAME = ""\"$NAME"\" >> github_secrets.py
else
    gum confirm "Do you want to remove the old file?" && rm 'github_secrets.py' && echo "GITHUB_API_TOKEN = ""\"$TOKEN"\" >> github_secrets.py && echo "USERNAME = ""\"$NAME"\" >> github_secrets.py || echo "file no removed"
fi

# echo "GITHUB_API_TOKEN = ""$TOKEN" >> name.txt
# echo "USERNAME = ""$NAME" >> name.txt
